version: '2'
 
 
services:
    web:
      build:
        context: .
        dockerfile: Dockerfile
      container_name: taller4-app
      ports:
      - "8087:6000"
    db:
      image: mongo:latest
      container_name: db
      volumes:
      - mongodb:/data/db
      - mongodb_config:/data/configdb
      ports:
      - 27017:27017
      command: mongod
  
volumes:
  mongodb:
  mongodb_config: